name: shopping_app
description: Online Shopping App.
publish_to:
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  flutter_riverpod: ^2.3.6
  go_router: ^9.0.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
